### ISSUE TITLE
Comparison with particle4dev/upload-avatar

### ISSUE THREAD

**Issue by dandv** [barbatus/upload-avatar-meteor#3]
Hi @Barbatus,

I'm a moderator o Atmosphere. I've noticed that your package https://atmospherejs.com/barbatus/upload-avatar seems to be an exact copy of
@particle4dev's https://atmospherejs.com/particle4dev/upload-avatar

If that is not the case, can you please update package.js to point to this repo, and explain to user what the difference are in this fork?

Otherwise, if this package was just a test, you can hide it from Atmosphere searches while letting it be installable by dependencies by running:

```
meteor admin set-unmigrated barbatus:upload-avatar
```

Thanks for keeping Atmosphere clean,
Dan

**Comment by barbatus** [comment]
Done
